AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Gemspec/RequireMFA:
  Exclude:
    - '**/*.gemspec'

Layout/LineLength:
  Max: 80

Metrics:
  Exclude:
    - 'spec/**/*.rb'

# For some reason, Metrics disable doesn't cover this
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Naming/FileName:
  Exclude:
    - 'lib/aws-sdk-core.rb'

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'lib/aws-sdk-core.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*.rb'

#Metrics:
#  Exclude:
#    - 'spec/**/*.rb'
#    - 'lib/aws/sdk/core/ini_parser.rb'
#

#
#Metrics/MethodLength:
#  Max: 15
#

