source 'https://rubygems.org'

# Use the latest hearth from Github
gem 'hearth', git: 'https://github.com/awslabs/smithy-ruby', glob: 'hearth/hearth.gemspec'

gem 'jmespath'
gem 'rexml'
gem 'rspec'
gem 'simplecov'
gem 'rubocop'
