require: rubocop-rake

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.0

Gemspec/RequireMFA:
  Exclude:
    - '**/*.gemspec'

Layout/LineLength:
  Max: 80

Metrics:
  Exclude:
    - '**/spec/**/*.rb'
    - 'gems/aws-sigv4/lib/aws-sigv4/signer.rb'
    - 'gems/aws-sdk-core/lib/aws-sdk-core/sso_bearer_provider.rb'

# For some reason, Metrics disable doesn't cover this
Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*.rb'

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  CountKeywordArgs: false

Naming/FileName:
  Exclude:
    - 'gems/aws-sdk-core/lib/aws-sdk-core.rb'
    - 'gems/aws-sigv4/lib/aws-sigv4.rb'
    - 'gems/aws-sdk-core/spec/aws-sdk-core_spec.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Exclude:
    - '**/spec/**/*.rb'
