# frozen_string_literal: true

# This Gemfile is copied into generated protocol test SDKs

source 'https://rubygems.org'

# Use the latest hearth from Github
gem 'hearth', git: 'https://github.com/awslabs/smithy-ruby', glob: 'hearth/hearth.gemspec'

# gem 'aws-sdk-core', "~> 4", path: 'TODO'

gem 'jmespath'
gem 'rexml'
gem 'rspec'
