AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Gemspec/RequireMFA:
  Exclude:
    - '**/*.gemspec'

Layout/LineLength:
  Max: 80

Metrics:
  Exclude:
    - '**/spec/**/*.rb'

# For some reason, Metrics disable doesn't cover this
Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*.rb'

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  CountKeywordArgs: false

Naming/FileName:
  Exclude:
    - 'aws-sdk-core/lib/aws-sdk-core.rb'
    - 'aws-sdk-core/spec/aws-sdk-core/aws-sdk-core_spec.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Exclude:
    - '**/spec/**/*.rb'
