name: Benchmark

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  id-token: write # required for OIDC
  contents: read

jobs:
  benchmark:
    runs-on: ubuntu-latest
    env:
      GH_EVENT: ${{github.event_name}}
      GH_REF: ${{github.head_ref}}
      GH_REPO: ${{github.repository}}
      EXECUTION_ENV: github-action
    strategy:
      fail-fast: false
      matrix:
        # Supported ruby versions
        ruby: [3.3] # [jruby-9.4, '3.0', 3.1, 3.2, 3.3]

    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - uses: actions/checkout@v4

      - name: Install gems
        run: bundle install

      - name: Benchmark gems
        run: bundle exec rake benchmark:run

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::373952703873:role/BenchmarkReporter
          role-session-name: benchmark-reporter
          aws-region: us-east-1

      - name: Upload benchmark report
        run: bundle exec rake benchmark:upload-report

      - name: Put benchmark metrics
        run: bundle exec rake benchmark:put-metrics
