name: Gems CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.0] #, 3.1, 3.2]

    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - uses: actions/checkout@v2

      - name: Install gems
        run: bundle install

      - name: Unit tests
        # TODO - run all when possible
        run: bundle exec rspec gems/aws-sdk-core gems/aws-sigv4

  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - uses: actions/checkout@v2

      - name: Install gems
        run: bundle install
        working-directory: gems/aws-sdk-core

      - name: Rubocop
        run: bundle exec rubocop -E -S
        working-directory: gems/aws-sdk-core
