name: Gems CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.0] #, 3.1, 3.2, 3.3]

    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - uses: actions/checkout@v2

      - name: Install gems
        run: bundle install

      - name: SigV4 Unit tests
        run: bundle exec rspec gems/aws-sigv4

      - name: Core Unit tests
        run: bundle exec rspec gems/aws-sdk-core

      - name: Gem Unit tests
        run: bundle exec rspec gems/ --exclude-pattern "gems/aws-sdk-core" --exclude-pattern "gems/aws-sigv4"

  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Ruby 3.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3

      - uses: actions/checkout@v2

      - name: Install gems
        run: bundle install

      - name: Rubocop
        run: bundle exec rubocop -E -S gems/aws-sdk-core gems/aws-sigv4
