name: Gems CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  java_version: 17
  ruby_version: 3.2

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.0] #, 3.1, 3.2, 3.3]

    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}

      - name: Build and publish latest smithy-ruby from github to maven local
        run: |
          git clone --depth 1 https://github.com/smithy-lang/smithy-ruby.git
          cd smithy-ruby
          bundle install
          bundle exec rake codegen:publish-local
      
      - name: Install gems
        run: |
          bundle config set --local without 'repl'
          bundle install
          
      - name: Build gems
        run: bundle exec rake codegen:build

      - name: Unit tests
        run: bundle exec rake test

  rubocop-core:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby_version }}

      - uses: actions/checkout@v2

      - name: Install gems
        run: bundle install

      - name: Rubocop Core
        run: bundle exec rake rubocop:core

  rubocop-codegen:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby_version }}

      - uses: actions/checkout@v2

      - name: Install gems
        run: bundle install

      - name: Rubocop Codegen
        run: bundle exec rake rubocop:codegen
