name: Protocol Test CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  java_version: 17

jobs:
  generate-test-sdks:
    name: Generate the test sdk
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.java_version }}
    - name: Build and publish maven local smithy-ruby
      run: |
        git clone --depth 1 https://github.com/awslabs/smithy-ruby.git
        cd smithy-ruby/codegen
        ./gradlew clean build publishToMavenLocal
        cd ../..
    - name: Run generator
      working-directory: codegen
      run:
        ./gradlew :protocol-test-codegen:build
    - name: Upload AWS Query Protocol Test SDK
      uses: actions/upload-artifact@v2
      with:
        name: aws_query
        path: codegen/protocol-test-codegen/build/smithyprojections/protocol-test-codegen/aws-protocoltests-query/ruby-codegen/aws_query
    - name: Upload AWS EC2 Protocol Test SDK
      uses: actions/upload-artifact@v2
      with:
        name: aws_ec2
        path: codegen/protocol-test-codegen/build/smithyprojections/protocol-test-codegen/aws-protocoltests-ec2/ruby-codegen/aws_ec2
    - name: Upload JSON 1.0 Protocol Test SDK
      uses: actions/upload-artifact@v2
      with:
        name: json_rpc_10
        path: codegen/protocol-test-codegen/build/smithyprojections/protocol-test-codegen/aws-protocoltests-json10/ruby-codegen/json_rpc_10
    - name: Upload JSON 1.1 Protocol Test SDK
      uses: actions/upload-artifact@v2
      with:
        name: json_protocol
        path: codegen/protocol-test-codegen/build/smithyprojections/protocol-test-codegen/aws-protocoltests-json/ruby-codegen/json_protocol
    - name: Upload Rest XML Protocol Test SDK
      uses: actions/upload-artifact@v2
      with:
        name: rest_xml
        path: codegen/protocol-test-codegen/build/smithyprojections/protocol-test-codegen/aws-protocoltests-restxml/ruby-codegen/rest_xml
    - name: Upload Rest JSON Protocol Test SDK
      uses: actions/upload-artifact@v2
      with:
        name: rest_json
        path: codegen/protocol-test-codegen/build/smithyprojections/protocol-test-codegen/aws-protocoltests-restjson/ruby-codegen/rest_json
    - name: Upload Rest JSON Extras Protocol Test SDK
      uses: actions/upload-artifact@v2
      with:
        name: rest_json_extras
        path: codegen/protocol-test-codegen/build/smithyprojections/protocol-test-codegen/aws-protocoltests-restjson-extras/ruby-codegen/rest_json_extras
    - name: Upload Rest XML Extras Protocol Test SDK
      uses: actions/upload-artifact@v2
      with:
        name: rest_xml_extras
        path: codegen/protocol-test-codegen/build/smithyprojections/protocol-test-codegen/aws-protocoltests-restxml-extras/ruby-codegen/rest_xml_extras
    - name: Upload EC2 Query Extras Protocol Test SDK
      uses: actions/upload-artifact@v2
      with:
        name: aws_ec2_extras
        path: codegen/protocol-test-codegen/build/smithyprojections/protocol-test-codegen/aws-protocoltests-ec2-extras/ruby-codegen/aws_ec2_extras
    - name: Upload Query Extras Protocol Test SDK
      uses: actions/upload-artifact@v2
      with:
        name: aws_query_extras
        path: codegen/protocol-test-codegen/build/smithyprojections/protocol-test-codegen/aws-protocoltests-query-extras/ruby-codegen/aws_query_extras

  protocol-specs:
    needs: [generate-test-sdks]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.0, 3.1, 3.2]
        protocol: [aws_query, aws_ec2, json_rpc_10, json_protocol, rest_xml, rest_json, rest_json_extras, rest_xml_extras, aws_ec2_extras, aws_query_extras]

    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - uses: actions/checkout@v2

      - name: Download generated test sdk
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.protocol }}
          path: ${{ matrix.protocol }}

      - name: Copy Gemfile
        run: |
          cp Gemfile ${{ matrix.protocol }}

      - name: Install gems
        run: |
          bundle config set --local without 'repl'
          bundle install
        working-directory: ./${{ matrix.protocol }}

      - name: Tests
        run: bundle exec rspec -I ../gems/aws-sdk-core/lib -I ../gems/aws-sigv4/lib
        working-directory: ./${{ matrix.protocol }}