name: Protocol Test CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  java_version: 17

jobs:
  protocol-specs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.0] #[3.0, 3.1, 3.2]
        protocol: [aws_query, aws_ec2, json_rpc_10, json_protocol, rest_xml, rest_json, rest_json_extras, rest_xml_extras, aws_ec2_extras, aws_query_extras]

    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}

      - name: Build and publish latest smithy-ruby from github to maven local
        run: |
          git clone --depth 1 https://github.com/smithy-lang/smithy-ruby.git
          cd smithy-ruby
          bundle install
          bundle exec rake codegen:publish-local
      
      - name: Install gems
        run: |
          bundle config set --local without 'repl'
          bundle install
          
      - name: Build test sdks
        run: bundle exec rake codegen:build:protocol-test-codegen

      - name: Run Protocol Tests
        run: bundle exec rake test:protocol:${{ matrix.protocol }}
